#!/usr/bin/env bash

#
# Tail the Tomcat logs
#

if [ -z "$TOMCAT_HOME" ]; then
  echo "You must define TOMCAT_HOME" 1>&2
  exit 1;
fi

echo Sleeping for 5 seconds
sleep 5

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  tail --lines=50 -f $TOMCAT_HOME/logs/*
else
  tail -50f $TOMCAT_HOME/logs/*
fi

